---
title: "How-Big-Cheatsheet"
author: "Steve Simon"
date: "September 17, 2016"
output: html_document
---

The first figure illustrates the margins. Start with the assumption that the graph is seven inches by seven inches and that mar=c(5.1, 4.1, 4.1, 2.1) and mai=c(1.02, 0.82, 0.82, 0.42) which means 5 lines per inch. Also assume that there are 96 pixels per inch.

```{r margins, fig.width=5.25, fig.height=5.25}
x <- function(p) {
  marks <- c(-1, 0, 0.82, 7-0.42, 6.9, 6.9)
  p <- ifelse (p < 100, 100, p)
  p <- ifelse (p > 500, 500, p)
  i <- p %/% 100
  w <- (p/100) %% 1
  return((1-w)*marks[i]+w*marks[i+1])
}

y <- function(p) {
  marks <- c(-1, 0, 1.02, 7-0.82, 6.9, 6.9)
  p <- ifelse (p < 100, 100, p)
  p <- ifelse (p > 500, 500, p)
  i <- p %/% 100
  w <- (p/100) %% 1
  return((1-w)*marks[i]+w*marks[i+1])
}

par(mar=rep(0, 4), xaxs="i", yaxs="i")
plot(c(-1,7), c(-1,7), type="n", axes=FALSE)

# user coordinates after adding 4%
polygon(
  x=x(c(300, 400, 400, 300)),
  y=y(c(300, 300, 400, 400)),
  density=NA, col="olivedrab1", border="black")

# user coordinates defined by xlim, ylim
polygon(
  x=x(c(304, 396, 396, 304)),
  y=y(c(304, 304, 396, 396)),
  density=NA, col="olivedrab", border="black", lty="dotted")

# graphics device size (x)
s1 <- "fin[1] (in)"
w1 <- strwidth(s1)
text    (x(304),    y(150), s1, adj=0)
arrows  (x(300),    y(150), x(200), y(150), lwd=3, len=0.05)
arrows  (x(308)+w1, y(150), x(500), y(150), lwd=3, len=0.05)
segments(x(200),    y(190), x(200), y(110), lwd=3)
segments(x(500),    y(190), x(500), y(110), lwd=3)

# graphics device size (y)
s2 <- "fin[2] (in)"
w2 <- strwidth(s2)
text    (x(150), y(304), s2, adj=0, srt=90)
arrows  (x(150), y(300),    x(150), y(200), lwd=3, len=0.05)
arrows  (x(150), y(308)+w2, x(150), y(500), lwd=3, len=0.05)
segments(x(190), y(200),    x(110), y(200), lwd=3)
segments(x(190), y(500),    x(110), y(500), lwd=3)

# plotting region size (x--pin[1], plt[1], plt[2])
s3 <- "pin[1] (in)"
w3 <- strwidth(s3)
text  (x(312),    y(330), s3, adj=0)
arrows(x(308),    y(330), x(300), y(330), lwd=3, len=0.05)
arrows(x(316)+w3, y(330), x(400), y(330), lwd=3, len=0.05)

s4 <- "plt[1] (pct)"
w4 <- strwidth(s4)
text    (x(312), y(310), s4, adj=0)
arrows  (x(200), y(310), x(300),    y(310), lwd=3, len=0.05)
segments(x(300), y(310), x(308),    y(310), lwd=3, lty="dotted")
segments(x(500), y(310), x(316)+w4, y(310), lwd=3, lty="dotted")

s5 <- "plt[2] (pct)"
w5 <- strwidth(s5)
text    (x(312),    y(320), s5, adj=0)
segments(x(200),    y(320), x(308), y(320), lwd=3)
arrows  (x(316)+w5, y(320), x(400), y(320), lwd=3, len=0.05)
segments(x(400),    y(320), x(500), y(320), lwd=3, lty="dotted")

s6 <- "pin[2] (in)"
w6 <- strwidth(s6)
arrows(x(390), y(371)-w6, x(390), y(300), lwd=3, len=0.05)
arrows(x(390), y(379),    x(390), y(400), lwd=3, len=0.05)
text  (x(390), y(375), s6, adj=1, srt=90)

# plotting region size (x--pin[1], plt[1], plt[2])
s7 <- "plt[4] (pct)"
w7 <- strwidth(s7)
text    (x(380), y(375), s7, adj=1, srt=90)
segments(x(380), y(200), x(380), y(371)-w7, lwd=3)
arrows  (x(380), y(379), x(380), y(400),    lwd=3, len=0.05)
segments(x(380), y(400), x(380), y(500),    lwd=3, lty="dotted")

s8 <- "plt[3] (pct)"
w8 <- strwidth(s8)
text    (x(370), y(375), s8, adj=1, srt=90)
segments(x(370), y(200), x(370), y(371)-w7, lwd=3, lty="dotted")
arrows  (x(370), y(200), x(370), y(300),    lwd=3, len=0.05)
segments(x(370), y(379), x(370), y(500),    lwd=3, lty="dotted")


# lower left user coordinates, usr[c(1,3)] (user)
arrows  (x(267), y(267), x(300), y(300), lwd=3, len=0.05)
segments(x(267), y(267), x(314), y(267), lwd=3)
text    (x(318), y(267), "usr[c(1,3)] (user)", adj=0)

# upper right user coordinates, usr[c(2,4)] (user)
arrows  (x(433), y(433), x(400), y(400), lwd=3, len=0.05)
segments(x(433), y(433), x(360), y(433), lwd=3)
text    (x(356), y(433), "usr[c(2,4)] (user)", adj=1)

# bottom margin, mai[1] (in), mar[1] (lines)
arrows  (x(308), y(200), x(308), y(300), lwd=3, len=0.05, code=3)
segments(x(308), y(233), x(314), y(233), lwd=3)
text(    x(318), y(233), "mai[1] (in), mar[1] (lines)", adj=0, cex=1.0)

# top margin, mai[3] (in), nmar[3] (lines)
arrows  (x(366), y(400), x(366), y(500), lwd=3, len=0.05, code=3)
segments(x(366), y(467), x(360), y(467), lwd=3)
text    (x(356), y(467), "mai[3] (in), nmar[3] (lines)", adj=1, cex=1.0)

# left margin, mai[2] (in), mar[2] (lines)
arrows  (x(200), y(392), x(300), y(392), lwd=3, len=0.05, code=3)
segments(x(250), y(392), x(250), y(386), lwd=3)
text    (x(250), y(382), "mai[2] (in), mar[2] (lines)", adj=1, srt=90)

# right margin, mai[4] (in), nmar[4] (lines)
arrows  (x(400), y(334), x(500), y(334), lwd=3, len=0.05, code=3)
segments(x(450), y(334), x(450), y(340), lwd=3)
text    (x(450), y(344), "mai[4] (in), nmar[4] (lines)", adj=0, srt=90, cex=1.0)

axis(side=1, pos=y(300), at=x(c(304, 396)), labels=rep(" ", 2), lwd=3) 
axis(side=2, pos=x(300), at=y(c(304, 396)), labels=rep(" ", 2), lwd=3) 

polygon(x=x(c(200, 500, 500, 200)), y=y(c(200, 200, 500, 500)), lwd=3, lty="dashed")
```

```{r string-size, fig.width=2.62, fig.height=2.62}
par(mar=c(2.1, 2.1, 0.1, 0.1))
# test
plot(c(1:10,9:1))
par("cin")
par("cra")
par("csi")
par("cxy")

s <- "gh"
text(10, 5, s, cex=3)
text( 6, 5, "h", cex=3)
text( 3, 5, "g", cex=3)
# test
x <- 1
Hi.width.user <- strwidth(s, units="user", cex=3)
print(Hi.width.user)
Hi.height.user <- strheight(s, units="user", cex=3)
print(Hi.height.user)
x.box <- 10+c(-1,-1,1,1)*Hi.width.user/2
y.box <-  5+c(-1,1,1,-1)*Hi.height.user/2
polygon(x=x.box,y=y.box,border="red")
```

